### ISSUE TITLE
Let the battle begin

### ISSUE THREAD

**Issue by jimmcnulty41** [wikitree-website/wikitree-page#1]
https://github.com/jimmcnulty41/wikitree.website

**Comment by alexburner** [comment]
Tree wars! Good luck in there, seeing `bower` and `angular ~1.3.x`

**Comment by jimmcnulty41** [comment]
Nevermind the battle is off I need ur help

**Comment by jimmcnulty41** [comment]
I thought I couldn't log issues in the master repo, but I was wrong

**Comment by alexburner** [comment]
Hi GitHub Notifications are the worst I am just now seeing this

What's the issue??
